name: 'dbt_retailco'
version: '1.0.0'
config-version: 2
profile: 'dbt_retailco'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  dbt_retailco:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

snapshots:
  dbt_retailco:
    +target_schema: snapshots