FROM apache/airflow:2.9.2

USER root
RUN apt-get update -q && apt-get install -y git -q

USER airflow
RUN pip install --no-cache-dir \
    dbt-core \
    dbt-postgres \
    dlt[postgres] \
    sqlalchemy \
    requests==2.31.0 \
    psycopg2-binary==2.9.9 \
    python-dotenv==1.0.0
